In [1]:
import pandas as pd

branches_df = pd.read_csv("Branches.csv")
products_df = pd.read_csv("Products.csv")
branch_aliases_df = pd.read_csv("BranchAliases.csv")
product_aliases_df = pd.read_csv("ProductAliases.csv")
research_notes_df = pd.read_csv("Branch_Product_Research_Notes.csv")

orders_raw_df = pd.read_csv("Orders_Raw.csv")
order_items_raw_df = pd.read_csv("OrderItems_Raw.csv")
daily_ops_raw_df = pd.read_csv("DailyBranchOperations_Raw.csv")
product_availability_raw_df = pd.read_csv("ProductAvailability_Raw.csv")

In [2]:
def inspect_branches(df):
    df.info()
    display(df.head())
    print(df.isnull().sum())
    print("Duplicates:", df.duplicated().sum())
    print("BranchID Duplicates:", df["BranchID"].duplicated().sum())

inspect_branches(branches_df)

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BranchID             20 non-null     str
 1   BranchName_Standard  20 non-null     str
 2   Governorate          20 non-null     str
 3   AreaGroup            20 non-null     str
 4   Status               20 non-null     str
 5   Note                 20 non-null     str
dtypes: str(6)
memory usage: 1.1 KB

,BranchID,BranchName_Standard,Governorate,AreaGroup,Status,Note
0,BR001,مدينة نصر - عباس العقاد,Cairo,East Cairo,Illustrative,Synthetic training scenario; illustrative loca...
1,BR002,مصر الجديدة - الكوربة,Cairo,East Cairo,Illustrative,Synthetic training scenario; illustrative loca...
2,BR003,التجمع الخامس,Cairo,New Cairo,Illustrative,Synthetic training scenario; illustrative loca...
3,BR004,المعادي,Cairo,South Cairo,Illustrative,Synthetic training scenario; illustrative loca...
4,BR005,وسط البلد,Cairo,Central Cairo,Illustrative,Synthetic training scenario; illustrative loca...

BranchID               0
BranchName_Standard    0
Governorate            0
AreaGroup              0
Status                 0
Note                   0
dtype: int64
Duplicates: 0
BranchID Duplicates: 0

In [3]:
branches_df.columns = branches_df.columns.str.strip()

for col in branches_df.select_dtypes(include="object").columns:
    branches_df[col] = branches_df[col].astype(str).str.strip()

branches_df.drop_duplicates(inplace=True)

branches_df.head()

C:\Users\mohamed\AppData\Local\Temp\ipykernel_15724\3115344349.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in branches_df.select_dtypes(include="object").columns:

,BranchID,BranchName_Standard,Governorate,AreaGroup,Status,Note
0,BR001,مدينة نصر - عباس العقاد,Cairo,East Cairo,Illustrative,Synthetic training scenario; illustrative loca...
1,BR002,مصر الجديدة - الكوربة,Cairo,East Cairo,Illustrative,Synthetic training scenario; illustrative loca...
2,BR003,التجمع الخامس,Cairo,New Cairo,Illustrative,Synthetic training scenario; illustrative loca...
3,BR004,المعادي,Cairo,South Cairo,Illustrative,Synthetic training scenario; illustrative loca...
4,BR005,وسط البلد,Cairo,Central Cairo,Illustrative,Synthetic training scenario; illustrative loca...

In [4]:
branch_aliases_df.info()
display(branch_aliases_df.head(10))
print(branch_aliases_df.isnull().sum())
print("Duplicates:", branch_aliases_df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   BranchName_Alias  115 non-null    str
 1   BranchID          115 non-null    str
dtypes: str(2)
memory usage: 1.9 KB

             BranchName_Alias BranchID
0     مدينة نصر - عباس العقاد    BR001
1       مدينة نصر عباس العقاد    BR001
2                   مدينة نصر    BR001
3    Nasr City Abbas El Akkad    BR001
4  Nasr City - Abbas El Akkad    BR001
5            nasr city branch    BR001
6                 عباس العقاد    BR001
7      مدينة نصر  عباس العقاد    BR001
8                    NasrCity    BR001
9       مصر الجديدة - الكوربة    BR002

BranchName_Alias    0
BranchID            0
dtype: int64
Duplicates: 0

In [5]:
branch_aliases_df.columns = branch_aliases_df.columns.str.strip()

for col in branch_aliases_df.select_dtypes(include="object").columns:
    branch_aliases_df[col] = branch_aliases_df[col].astype(str).str.strip()

branch_aliases_df.drop_duplicates(inplace=True)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_15724\311546437.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in branch_aliases_df.select_dtypes(include="object").columns:

In [6]:
products_df.info()
display(products_df.head(10))
print(products_df.isnull().sum())
print("Duplicates:", products_df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ProductID                33 non-null     str
 1   ProductName_Standard_AR  33 non-null     str
 2   ProductName_Standard_EN  33 non-null     str
 3   ProductFamily            33 non-null     str
 4   Category                 33 non-null     str
 5   ReferencePrice_EGP       33 non-null     int64
 6   Note                     33 non-null     str
dtypes: int64(1), str(6)
memory usage: 1.9 KB

,ProductID,ProductName_Standard_AR,ProductName_Standard_EN,ProductFamily,Category,ReferencePrice_EGP,Note
0,PR001,أرز بلبن سادة,Plain Rice Pudding,Rice Pudding,Rice Pudding,35,Synthetic reference price for training; not a ...
1,PR002,أرز بلبن مكسرات,Rice Pudding Nuts,Rice Pudding,Rice Pudding,48,Synthetic reference price for training; not a ...
2,PR003,أرز بلبن لوتس,Lotus Rice Pudding,Rice Pudding,Rice Pudding,55,Synthetic reference price for training; not a ...
3,PR004,أم علي,Om Ali,Oven Dessert,Oven Dessert,52,Synthetic reference price for training; not a ...
4,PR005,كنافة مانجو,Mango Kunafa,Kunafa,Kunafa,68,Synthetic reference price for training; not a ...
5,PR006,كنافة نوتيلا,Nutella Kunafa,Kunafa,Kunafa,72,Synthetic reference price for training; not a ...
6,PR007,كنافة قشطة,Cream Kunafa,Kunafa,Kunafa,60,Synthetic reference price for training; not a ...
7,PR008,كشري مانجو,Mango Koshary,Layered Dessert,Layered Dessert,65,Synthetic reference price for training; not a ...
8,PR009,كشري لوتس,Lotus Koshary,Layered Dessert,Layered Dessert,70,Synthetic reference price for training; not a ...
9,PR010,بسبوسة سادة,Plain Basbousa,Basbousa,Basbousa,32,Synthetic reference price for training; not a ...

ProductID                  0
ProductName_Standard_AR    0
ProductName_Standard_EN    0
ProductFamily              0
Category                   0
ReferencePrice_EGP         0
Note                       0
dtype: int64
Duplicates: 0

In [7]:
products_df.columns = products_df.columns.str.strip()

for col in products_df.select_dtypes(include="object").columns:
    products_df[col] = products_df[col].astype(str).str.strip()

products_df.drop_duplicates(inplace=True)

products_df.head()

C:\Users\mohamed\AppData\Local\Temp\ipykernel_15724\1109806991.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in products_df.select_dtypes(include="object").columns:

,ProductID,ProductName_Standard_AR,ProductName_Standard_EN,ProductFamily,Category,ReferencePrice_EGP,Note
0,PR001,أرز بلبن سادة,Plain Rice Pudding,Rice Pudding,Rice Pudding,35,Synthetic reference price for training; not a ...
1,PR002,أرز بلبن مكسرات,Rice Pudding Nuts,Rice Pudding,Rice Pudding,48,Synthetic reference price for training; not a ...
2,PR003,أرز بلبن لوتس,Lotus Rice Pudding,Rice Pudding,Rice Pudding,55,Synthetic reference price for training; not a ...
3,PR004,أم علي,Om Ali,Oven Dessert,Oven Dessert,52,Synthetic reference price for training; not a ...
4,PR005,كنافة مانجو,Mango Kunafa,Kunafa,Kunafa,68,Synthetic reference price for training; not a ...

In [8]:
product_aliases_df.info()
display(product_aliases_df.head(10))
print(product_aliases_df.isnull().sum())
print("Duplicates:", product_aliases_df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ProductName_Alias  130 non-null    str
 1   ProductID          130 non-null    str
dtypes: str(2)
memory usage: 2.2 KB

    ProductName_Alias ProductID
0       أرز بلبن سادة     PR001
1       ارز بلبن ساده     PR001
2        رز بلبن سادة     PR001
3  Rice Pudding Plain     PR001
4  Plain rice pudding     PR001
5       رز بلبن ساده      PR001
6     أرز باللبن سادة     PR001
7     أرز بلبن مكسرات     PR002
8     ارز بلبن مكسرات     PR002
9   Rice Pudding Nuts     PR002

ProductName_Alias    0
ProductID            0
dtype: int64
Duplicates: 0

In [9]:
product_aliases_df.columns = product_aliases_df.columns.str.strip()

for col in product_aliases_df.select_dtypes(include="object").columns:
    product_aliases_df[col] = product_aliases_df[col].astype(str).str.strip()

product_aliases_df.drop_duplicates(inplace=True)

product_aliases_df.head()

C:\Users\mohamed\AppData\Local\Temp\ipykernel_15724\2123032895.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in product_aliases_df.select_dtypes(include="object").columns:

    ProductName_Alias ProductID
0       أرز بلبن سادة     PR001
1       ارز بلبن ساده     PR001
2        رز بلبن سادة     PR001
3  Rice Pudding Plain     PR001
4  Plain rice pudding     PR001

In [10]:
orders_raw_df.info()
display(orders_raw_df.head(10))
print(orders_raw_df.isnull().sum())
print("Duplicates:", orders_raw_df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 19000 entries, 0 to 18999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          19000 non-null  str
 1   OrderDateTime    19000 non-null  str
 2   BranchName_Raw   19000 non-null  str
 3   Channel          19000 non-null  str
 4   OrderStatus      19000 non-null  str
 5   CustomerCount    18572 non-null  float64
 6   DeliveryMinutes  7352 non-null   float64
dtypes: float64(2), str(5)
memory usage: 1.0 MB

,OrderID,OrderDateTime,BranchName_Raw,Channel,OrderStatus,CustomerCount,DeliveryMinutes
0,OR000001,2025-04-11 20:51:49,October 6,Takeaway,Completed,5.0,NaN
1,OR000002,2025-02-15 21:38:21,مدينة نصر,Delivery,Completed,1.0,43.0
2,OR000003,2025-03-27 20:12:48,Smouha Branch,In-Store,Cancelled,2.0,NaN
3,OR000004,2025-06-01 15:39:09,Sheikh Zayed,Takeaway,Completed,1.0,NaN
4,OR000005,2025-04-02 16:10:28,El Sheikh Zayed,In-Store,Completed,2.0,NaN
5,OR000006,2025-01-30 19:05:42,Mansoura Corniche,In-Store,Completed,1.0,NaN
6,OR000007,2025-05-08 18:01:38,وسط البلد,In-Store,Completed,2.0,NaN
7,OR000008,2025-01-25 19:54:05,Heliopolis Korba,In-Store,Completed,2.0,NaN
8,OR000009,2025-04-15 13:56:23,مدينة نصر عباس العقاد,In-Store,Completed,2.0,NaN
9,OR000010,2025-05-10 20:38:59,El Haram,Delivery,Completed,1.0,35.0

OrderID                0
OrderDateTime          0
BranchName_Raw         0
Channel                0
OrderStatus            0
CustomerCount        428
DeliveryMinutes    11648
dtype: int64
Duplicates: 0

In [11]:
orders_raw_df.columns = orders_raw_df.columns.str.strip()

for col in ["BranchName_Raw", "Channel", "OrderStatus"]:
    orders_raw_df[col] = orders_raw_df[col].astype(str).str.strip()

orders_raw_df["OrderDateTime"] = pd.to_datetime(orders_raw_df["OrderDateTime"])

orders_raw_df["CustomerCount"] = orders_raw_df["CustomerCount"].fillna(1)

orders_raw_df = orders_raw_df.merge(
    branch_aliases_df[["BranchName_Alias", "BranchID"]],
    left_on="BranchName_Raw",
    right_on="BranchName_Alias",
    how="left",
)

orders_raw_df.drop(columns=["BranchName_Alias"], inplace=True)

orders_raw_df.drop_duplicates(inplace=True)

display(orders_raw_df.head())
print("فروع لم يتم التعرف عليها (Nulls in BranchID):", orders_raw_df["BranchID"].isnull().sum())

,OrderID,OrderDateTime,BranchName_Raw,Channel,OrderStatus,CustomerCount,DeliveryMinutes,BranchID
0,OR000001,2025-04-11 20:51:49,October 6,Takeaway,Completed,5.0,NaN,BR007
1,OR000002,2025-02-15 21:38:21,مدينة نصر,Delivery,Completed,1.0,43.0,BR001
2,OR000003,2025-03-27 20:12:48,Smouha Branch,In-Store,Cancelled,2.0,NaN,BR010
3,OR000004,2025-06-01 15:39:09,Sheikh Zayed,Takeaway,Completed,1.0,NaN,BR006
4,OR000005,2025-04-02 16:10:28,El Sheikh Zayed,In-Store,Completed,2.0,NaN,BR006

فروع لم يتم التعرف عليها (Nulls in BranchID): 248

In [12]:
orders_raw_df[orders_raw_df["BranchID"].isnull()]["BranchName_Raw"].value_counts()

BranchName_Raw
مدينة نصر عباس العقادد        19
المنصورة المشايه الجديدة      16
الاسكندريه سموحه الجديدة      15
HARAM BRANCH                  10
EL HARAM                       9
ALEXANDRIA SMOUHA              9
MAADI BRANCH                   8
PYRAMIDS ROAD                  8
DOKKI BRANCH                   7
HARAM                          7
HELIOPOLIS KORBA               7
KORBA BRANCH                   6
MAADI                          6
DOKKI                          6
NASRCITY                       6
NEW CAIRO FIFTH SETTLEMENT     6
SHEIKH ZAYED BRANCH            5
Dokii East                     5
SMOUHA BRANCH                  5
TAGAMOA KHAMES                 5
NASR CITY BRANCH               5
EL MANSOURA                    5
DOWNTOWN CAIRO                 4
ALEX - SMOUHA                  4
HELIOPOLIS - KORBA             4
NASR CITY ABBAS EL AKKAD       4
6 OCTOBER                      4
MANSOURA EL MASHAYA            4
SHEIKH ZAYED                   4
EL MAADI                       4
EL DOKKI                       4
NASR CITY - ABBAS EL AKKAD     4
FIFTH SETTLEMENT               3
SIDI GABER                     3
SMOUHA                         3
OCTOBER 6                      3
SIDI GABER BRANCH              3
CAIRO DOWNTOWN                 3
ZAYED BRANCH                   3
6TH OF OCTOBER                 2
NEW CAIRO                      2
MASR EL GEDIDA                 2
EL SHEIKH ZAYED                2
ALEXANDRIA SIDI GABER          1
MANSOURA CORNICHE              1
DOWNTOWN BRANCH                1
OCTOBER BRANCH                 1
Name: count, dtype: int64

In [13]:
orders_raw_df["BranchName_Clean"] = (
    orders_raw_df["BranchName_Raw"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

branch_aliases_df["Alias_Clean"] = (
    branch_aliases_df["BranchName_Alias"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

orders_raw_df["BranchID"] = orders_raw_df["BranchName_Clean"].map(
    branch_aliases_df.drop_duplicates("Alias_Clean").set_index("Alias_Clean")["BranchID"]
)

orders_raw_df.drop(columns=["BranchName_Clean"], inplace=True)

print("فروع لم يتم التعرف عليها بعد التعديل:", orders_raw_df["BranchID"].isnull().sum())

فروع لم يتم التعرف عليها بعد التعديل: 55

In [14]:
orders_raw_df[orders_raw_df["BranchID"].isnull()]["BranchName_Raw"].value_counts()

BranchName_Raw
مدينة نصر عباس العقادد      19
المنصورة المشايه الجديدة    16
الاسكندريه سموحه الجديدة    15
Dokii East                   5
Name: count, dtype: int64

In [15]:

unmapped_fixes = {
    "مدينة نصر عباس العقادد": "BR001",
    "المنصورة المشايه الجديدة": "BR013",
    "الاسكندريه سموحه الجديدة": "BR010",
    "Dokii East": "BR008",
}

for raw_name, b_id in unmapped_fixes.items():
    clean_target = raw_name.replace(" ", "").lower()
    mask = (
        orders_raw_df["BranchID"].isnull()
        & orders_raw_df["BranchName_Raw"]
        .astype(str)
        .str.replace(" ", "")
        .str.lower()
        .str.contains(clean_target, regex=False)
    )
    orders_raw_df.loc[mask, "BranchID"] = b_id


orders_raw_df.loc[
    orders_raw_df["BranchID"].isnull()
    & orders_raw_df["BranchName_Raw"].astype(str).str.contains("العقادد"),
    "BranchID",
] = "BR001"

print(
    "فروع لم يتم التعرف عليها بعد المعالجة النهائية:",
    orders_raw_df["BranchID"].isnull().sum(),
)

فروع لم يتم التعرف عليها بعد المعالجة النهائية: 0

In [16]:
order_items_raw_df.info()
display(order_items_raw_df.head(10))
print(order_items_raw_df.isnull().sum())
print("Duplicates:", order_items_raw_df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 36650 entries, 0 to 36649
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderItemID      36650 non-null  str
 1   OrderID          36650 non-null  str
 2   ProductName_Raw  36650 non-null  str
 3   Quantity         36650 non-null  int64
 4   UnitPrice_EGP    36257 non-null  float64
 5   DiscountPercent  36650 non-null  int64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.7 MB

,OrderItemID,OrderID,ProductName_Raw,Quantity,UnitPrice_EGP,DiscountPercent
0,OI0000001,OR000001,Plain rice pudding,1,35.0,0
1,OI0000002,OR000002,أرز بلبن لوتس,1,53.9,0
2,OI0000003,OR000003,مهلبيه,2,30.0,0
3,OI0000004,OR000004,كنافة بالمانجو,1,68.0,0
4,OI0000005,OR000004,Mahalabia,2,29.4,0
5,OI0000006,OR000004,أم علي,2,52.0,0
6,OI0000007,OR000005,Kunafa Oreo,1,72.1,5
7,OI0000008,OR000005,Mango Ice Cream,1,30.0,10
8,OI0000009,OR000005,Chocolate Waffle,3,62.0,10
9,OI0000010,OR000006,رز بلبن مكسرات,1,48.0,0

OrderItemID          0
OrderID              0
ProductName_Raw      0
Quantity             0
UnitPrice_EGP      393
DiscountPercent      0
dtype: int64
Duplicates: 0

In [17]:
order_items_raw_df.columns = order_items_raw_df.columns.str.strip()
order_items_raw_df["ProductName_Raw"] = order_items_raw_df["ProductName_Raw"].astype(str).str.strip()

order_items_raw_df["Prod_Clean"] = (
    order_items_raw_df["ProductName_Raw"]
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

product_aliases_df["Alias_Clean"] = (
    product_aliases_df["ProductName_Alias"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

order_items_raw_df["ProductID"] = order_items_raw_df["Prod_Clean"].map(
    product_aliases_df.drop_duplicates("Alias_Clean").set_index("Alias_Clean")["ProductID"]
)

order_items_raw_df.drop(columns=["Prod_Clean"], inplace=True)

display(order_items_raw_df.head())
print("منتجات لم يتم التعرف عليها (Nulls in ProductID):", order_items_raw_df["ProductID"].isnull().sum())

,OrderItemID,OrderID,ProductName_Raw,Quantity,UnitPrice_EGP,DiscountPercent,ProductID
0,OI0000001,OR000001,Plain rice pudding,1,35.0,0,PR001
1,OI0000002,OR000002,أرز بلبن لوتس,1,53.9,0,PR003
2,OI0000003,OR000003,مهلبيه,2,30.0,0,PR012
3,OI0000004,OR000004,كنافة بالمانجو,1,68.0,0,PR005
4,OI0000005,OR000004,Mahalabia,2,29.4,0,PR012

منتجات لم يتم التعرف عليها (Nulls in ProductID): 143

In [18]:
order_items_raw_df[order_items_raw_df["ProductID"].isnull()]["ProductName_Raw"].value_counts()

ProductName_Raw
كنافه مانجوو         35
Nutella Knafeh?      30
رز بلبن لوتس كبير    28
Oreo Kunaffa         25
مهابيه               20
NUTELLA KNAFEH?       3
OREO KUNAFFA          2
Name: count, dtype: int64

In [19]:
products_df[products_df["ProductName_Standard_AR"].str.contains("كنافة|لوتس|مهلب", regex=True)][["ProductID", "ProductName_Standard_AR", "ProductName_Standard_EN"]]

   ProductID ProductName_Standard_AR ProductName_Standard_EN
2      PR003           أرز بلبن لوتس      Lotus Rice Pudding
4      PR005             كنافة مانجو            Mango Kunafa
5      PR006            كنافة نوتيلا          Nutella Kunafa
6      PR007              كنافة قشطة            Cream Kunafa
8      PR009               كشري لوتس           Lotus Koshary
11     PR012                  مهلبية               Mahalabia
13     PR014             كنافة أوريو             Oreo Kunafa
22     PR023             قشطوطة لوتس         Lotus Kashtouta
31     PR032          كشري لوتس كبير     Large Lotus Koshary

In [20]:
item_fixes = {
    "مانجو": "PR005",    # كنافة مانجو
    "nutella": "PR006",  # كنافة نوتيلا
    "لوتس": "PR003",     # أرز بلبن لوتس
    "kunaffa": "PR014",  # كنافة أوريو
    "مهلب": "PR012",     # مهلبية
}

for keyword, p_id in item_fixes.items():
    mask = (
        order_items_raw_df["ProductID"].isnull()
        & order_items_raw_df["ProductName_Raw"]
        .astype(str)
        .str.replace(" ", "")
        .str.lower()
        .str.contains(keyword, regex=False)
    )
    order_items_raw_df.loc[mask, "ProductID"] = p_id

print("منتجات لم يتم التعرف عليها بعد المعالجة النهائية:", order_items_raw_df["ProductID"].isnull().sum())

منتجات لم يتم التعرف عليها بعد المعالجة النهائية: 20

In [21]:
order_items_raw_df.loc[
    order_items_raw_df["ProductID"].isnull()
    & order_items_raw_df["ProductName_Raw"].astype(str).str.contains("هلب|مهلب"),
    "ProductID",
] = "PR012"

print(
    "منتجات لم يتم التعرف عليها بعد التعديل الأخير:",
    order_items_raw_df["ProductID"].isnull().sum(),
)

منتجات لم يتم التعرف عليها بعد التعديل الأخير: 20

In [22]:
order_items_raw_df["ProductID"] = order_items_raw_df["ProductID"].fillna("PR012")

print("منتجات لم يتم التعرف عليها بعد المعالجة النهائية:", order_items_raw_df["ProductID"].isnull().sum())

منتجات لم يتم التعرف عليها بعد المعالجة النهائية: 0

In [23]:
price_map = products_df.set_index("ProductID")["ReferencePrice_EGP"]
order_items_raw_df["UnitPrice_EGP"] = order_items_raw_df["UnitPrice_EGP"].fillna(
    order_items_raw_df["ProductID"].map(price_map)
)

print("أسعار مفقودة بعد التعديل:", order_items_raw_df["UnitPrice_EGP"].isnull().sum())
display(order_items_raw_df.head())

أسعار مفقودة بعد التعديل: 0

,OrderItemID,OrderID,ProductName_Raw,Quantity,UnitPrice_EGP,DiscountPercent,ProductID
0,OI0000001,OR000001,Plain rice pudding,1,35.0,0,PR001
1,OI0000002,OR000002,أرز بلبن لوتس,1,53.9,0,PR003
2,OI0000003,OR000003,مهلبيه,2,30.0,0,PR012
3,OI0000004,OR000004,كنافة بالمانجو,1,68.0,0,PR005
4,OI0000005,OR000004,Mahalabia,2,29.4,0,PR012

In [24]:
daily_branch_ops_df = pd.read_csv("DailyBranchOperations_Raw.csv")

daily_branch_ops_df.info()
display(daily_branch_ops_df.head(10))
print(daily_branch_ops_df.isnull().sum())
print("Duplicates:", daily_branch_ops_df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 3620 entries, 0 to 3619
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   BusinessDate        3620 non-null   str
 1   BranchName_Raw      3620 non-null   str
 2   EstimatedFootfall   3620 non-null   int64
 3   StaffOnShift        3620 non-null   int64
 4   CustomerComplaints  3559 non-null   float64
 5   WasteKg             3534 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 169.8 KB

,BusinessDate,BranchName_Raw,EstimatedFootfall,StaffOnShift,CustomerComplaints,WasteKg
0,2025-01-01,Nasr City Abbas El Akkad,395,2,NaN,3.41
1,2025-01-01,الكوربه,483,5,2.0,1.86
2,2025-01-01,New Cairo Fifth Settlement,529,5,3.0,3.24
3,2025-01-01,Maadi Branch,341,2,0.0,3.59
4,2025-01-01,وسط البلد,544,6,1.0,3.75
5,2025-01-01,الشيخ زايد,360,5,NaN,3.20
6,2025-01-01,6 أكتوبر,432,4,0.0,3.14
7,2025-01-01,El Dokki,376,4,0.0,2.60
8,2025-01-01,الهرم,318,2,0.0,2.42
9,2025-01-01,Alexandria Smouha,469,4,1.0,3.48

BusinessDate           0
BranchName_Raw         0
EstimatedFootfall      0
StaffOnShift           0
CustomerComplaints    61
WasteKg               86
dtype: int64
Duplicates: 0

In [25]:
daily_branch_ops_df["BusinessDate"] = pd.to_datetime(daily_branch_ops_df["BusinessDate"])

daily_branch_ops_df["BranchName_Clean"] = (
    daily_branch_ops_df["BranchName_Raw"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

# 3. جلب كود الفرع من جدول الأسماء البديلة
daily_branch_ops_df["BranchID"] = daily_branch_ops_df["BranchName_Clean"].map(
    branch_aliases_df.drop_duplicates("Alias_Clean").set_index("Alias_Clean")["BranchID"]
)

daily_branch_ops_df.drop(columns=["BranchName_Clean"], inplace=True)

print("فروع لم يتم التعرف عليها (Nulls in BranchID):", daily_branch_ops_df["BranchID"].isnull().sum())
display(daily_branch_ops_df.head())

فروع لم يتم التعرف عليها (Nulls in BranchID): 4

,BusinessDate,BranchName_Raw,EstimatedFootfall,StaffOnShift,CustomerComplaints,WasteKg,BranchID
0,2025-01-01,Nasr City Abbas El Akkad,395,2,NaN,3.41,BR001
1,2025-01-01,الكوربه,483,5,2.0,1.86,BR002
2,2025-01-01,New Cairo Fifth Settlement,529,5,3.0,3.24,BR003
3,2025-01-01,Maadi Branch,341,2,0.0,3.59,BR004
4,2025-01-01,وسط البلد,544,6,1.0,3.75,BR005

In [26]:
daily_branch_ops_df[daily_branch_ops_df["BranchID"].isnull()]["BranchName_Raw"].value_counts()

BranchName_Raw
Alexx Smouha                    3
فرع المنصوره المشاية الجديدة    1
Name: count, dtype: int64

In [27]:
daily_branch_ops_df.loc[
    daily_branch_ops_df["BranchID"].isnull()
    & daily_branch_ops_df["BranchName_Raw"].astype(str).str.contains("Smouha", case=False),
    "BranchID"
] = "BR010"

daily_branch_ops_df.loc[
    daily_branch_ops_df["BranchID"].isnull()
    & daily_branch_ops_df["BranchName_Raw"].astype(str).str.contains("المنصور"),
    "BranchID"
] = "BR013"

print("فروع لم يتم التعرف عليها بعد التعديل:", daily_branch_ops_df["BranchID"].isnull().sum())

فروع لم يتم التعرف عليها بعد التعديل: 0

In [28]:
daily_branch_ops_df["CustomerComplaints"] = daily_branch_ops_df["CustomerComplaints"].fillna(0)

daily_branch_ops_df["WasteKg"] = daily_branch_ops_df.groupby("BranchID")["WasteKg"].transform(
    lambda x: x.fillna(x.mean())
)

print("القيم المفقودة المتبقية في الجدول بالكامل:")
print(daily_branch_ops_df.isnull().sum())

القيم المفقودة المتبقية في الجدول بالكامل:
BusinessDate          0
BranchName_Raw        0
EstimatedFootfall     0
StaffOnShift          0
CustomerComplaints    0
WasteKg               0
BranchID              0
dtype: int64

In [29]:
prod_avail_raw_df = pd.read_csv("ProductAvailability_Raw.csv")

prod_avail_raw_df.info()
display(prod_avail_raw_df.head(10))
print("القيم المفقودة:")
print(prod_avail_raw_df.isnull().sum())
print("التكرار (Duplicates):", prod_avail_raw_df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 12411 entries, 0 to 12410
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AvailabilityID      12411 non-null  str
 1   BusinessDate        12411 non-null  str
 2   BranchName_Raw      12411 non-null  str
 3   ProductName_Raw     12411 non-null  str
 4   AvailabilityStatus  12411 non-null  str
 5   StockUnits          12265 non-null  float64
dtypes: float64(1), str(5)
memory usage: 581.9 KB

,AvailabilityID,BusinessDate,BranchName_Raw,ProductName_Raw,AvailabilityStatus,StockUnits
0,AV0000001,2025-01-01,Tagamoa Khames,Om Ali,Available,36.0
1,AV0000002,2025-01-01,سموحة,Vanilla Ice Cream,Out of Stock,0.0
2,AV0000003,2025-01-01,وسط البلد,Muhallabia,Available,14.0
3,AV0000004,2025-01-01,الهرم,Mango Koshary,Available,21.0
4,AV0000005,2025-01-01,وسط البلد,آيس كريم فانيليا,Available,17.0
5,AV0000006,2025-01-01,مدينة نصر عباس العقاد,أرز بلبن مكسرات,Available,25.0
6,AV0000007,2025-01-01,المعادي,Plain Basbousa,Low Stock,1.0
7,AV0000008,2025-01-01,Maadi Branch,آيس كريم فانيليا,Available,21.0
8,AV0000009,2025-01-01,sheikh zayed branch,كشري بالمانجو,Available,36.0
9,AV0000010,2025-01-01,سيدي جابر,كشرى مانجو,Available,29.0

القيم المفقودة:
AvailabilityID          0
BusinessDate            0
BranchName_Raw          0
ProductName_Raw         0
AvailabilityStatus      0
StockUnits            146
dtype: int64
التكرار (Duplicates): 0

In [30]:
print("توزيع حالات التوفر للصفوف التي بها StockUnits فارغة:")
print(prod_avail_raw_df[prod_avail_raw_df["StockUnits"].isnull()]["AvailabilityStatus"].value_counts())

print("\nعينة من تلك الصفوف:")
display(prod_avail_raw_df[prod_avail_raw_df["StockUnits"].isnull()].head())

توزيع حالات التوفر للصفوف التي بها StockUnits فارغة:
AvailabilityStatus
Available       126
Low Stock        12
Out of Stock      8
Name: count, dtype: int64

عينة من تلك الصفوف:

,AvailabilityID,BusinessDate,BranchName_Raw,ProductName_Raw,AvailabilityStatus,StockUnits
238,AV0000239,2025-01-06,new cairo,ارز بلبن ساده,Available,NaN
242,AV0000243,2025-01-06,الاسكندرية سموحة,Choc Crepe,Out of Stock,NaN
328,AV0000329,2025-01-07,New Cairo Fifth Settlement,Vanilla Ice Cream,Available,NaN
525,AV0000526,2025-01-12,الشيخ زايد,Baked Rice Pudding,Available,NaN
589,AV0000590,2025-01-13,المنصورة - المشاية,رز بلبن ساده,Available,NaN

In [31]:
prod_avail_raw_df.groupby("AvailabilityStatus")["StockUnits"].agg(["count", "mean", "median"])

                    count       mean  median
AvailabilityStatus
Available           10064  24.306141    24.0
Low Stock            1652   3.812349     4.0
Out of Stock          549   0.003643     0.0

In [32]:
prod_avail_raw_df["BusinessDate"] = pd.to_datetime(prod_avail_raw_df["BusinessDate"])

stock_impute = {"Available": 24.0, "Low Stock": 4.0, "Out of Stock": 0.0}
for status, val in stock_impute.items():
    mask = (prod_avail_raw_df["AvailabilityStatus"] == status) & (prod_avail_raw_df["StockUnits"].isnull())
    prod_avail_raw_df.loc[mask, "StockUnits"] = val

# 3. تجهيز اسم الفرع وربطه بـ BranchID
prod_avail_raw_df["BranchName_Clean"] = (
    prod_avail_raw_df["BranchName_Raw"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

prod_avail_raw_df["BranchID"] = prod_avail_raw_df["BranchName_Clean"].map(
    branch_aliases_df.drop_duplicates("Alias_Clean").set_index("Alias_Clean")["BranchID"]
)
prod_avail_raw_df.drop(columns=["BranchName_Clean"], inplace=True)

print("قيم StockUnits المفقودة المتبقية:", prod_avail_raw_df["StockUnits"].isnull().sum())
print("فروع لم يتم التعرف عليها (Nulls in BranchID):", prod_avail_raw_df["BranchID"].isnull().sum())

قيم StockUnits المفقودة المتبقية: 0
فروع لم يتم التعرف عليها (Nulls in BranchID): 24

In [33]:
prod_avail_raw_df[prod_avail_raw_df["BranchID"].isnull()]["BranchName_Raw"].value_counts()

BranchName_Raw
Mansoura El Mashiaa       9
الشيخ زايد الجديدة فرع    8
Alexandria Smouhaaa       7
Name: count, dtype: int64

In [34]:
prod_avail_raw_df.loc[
    prod_avail_raw_df["BranchID"].isnull()
    & prod_avail_raw_df["BranchName_Raw"].astype(str).str.contains("Mansoura", case=False),
    "BranchID"
] = "BR013"

prod_avail_raw_df.loc[
    prod_avail_raw_df["BranchID"].isnull()
    & prod_avail_raw_df["BranchName_Raw"].astype(str).str.contains("زايد"),
    "BranchID"
] = "BR006"

prod_avail_raw_df.loc[
    prod_avail_raw_df["BranchID"].isnull()
    & prod_avail_raw_df["BranchName_Raw"].astype(str).str.contains("Smouha", case=False),
    "BranchID"
] = "BR010"

print("فروع لم يتم التعرف عليها بعد التعديل:", prod_avail_raw_df["BranchID"].isnull().sum())

فروع لم يتم التعرف عليها بعد التعديل: 0

In [35]:
prod_avail_raw_df["ProductName_Clean"] = (
    prod_avail_raw_df["ProductName_Raw"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

prod_avail_raw_df["ProductID"] = prod_avail_raw_df["ProductName_Clean"].map(
    product_aliases_df.drop_duplicates("Alias_Clean").set_index("Alias_Clean")["ProductID"]
)
prod_avail_raw_df.drop(columns=["ProductName_Clean"], inplace=True)

print("منتجات لم يتم التعرف عليها (Nulls in ProductID):", prod_avail_raw_df["ProductID"].isnull().sum())

منتجات لم يتم التعرف عليها (Nulls in ProductID): 21

In [36]:
prod_avail_raw_df[prod_avail_raw_df["ProductID"].isnull()]["ProductName_Raw"].value_counts()

ProductName_Raw
Mango Knafa Supreme    9
آيس كريم منجو          9
كنافة نوتيلااا         3
Name: count, dtype: int64

In [37]:
prod_avail_raw_df.loc[
    prod_avail_raw_df["ProductID"].isnull()
    & prod_avail_raw_df["ProductName_Raw"].astype(str).str.contains("Mango Knafa", case=False),
    "ProductID"
] = "PR005"

prod_avail_raw_df.loc[
    prod_avail_raw_df["ProductID"].isnull()
    & prod_avail_raw_df["ProductName_Raw"].astype(str).str.contains("آيس كريم منجو"),
    "ProductID"
] = "PR009"

prod_avail_raw_df.loc[
    prod_avail_raw_df["ProductID"].isnull()
    & prod_avail_raw_df["ProductName_Raw"].astype(str).str.contains("نوتيلا"),
    "ProductID"
] = "PR006"

# 2. فحص القيم المفقودة في الجدول بالكامل
print("منتجات لم يتم التعرف عليها بعد التعديل:", prod_avail_raw_df["ProductID"].isnull().sum())
print("\nالقيم المفقودة المتبقية في جدول ProductAvailability بالكامل:")
print(prod_avail_raw_df.isnull().sum())

منتجات لم يتم التعرف عليها بعد التعديل: 0

القيم المفقودة المتبقية في جدول ProductAvailability بالكامل:
AvailabilityID        0
BusinessDate          0
BranchName_Raw        0
ProductName_Raw       0
AvailabilityStatus    0
StockUnits            0
BranchID              0
ProductID             0
dtype: int64

In [41]:
import os

os.makedirs("cleaned_data", exist_ok=True)

# تصدير الجداول المعالجة
order_items_raw_df.to_csv("cleaned_data/Cleaned_OrderItems.csv", index=False)
daily_branch_ops_df.to_csv("cleaned_data/Cleaned_DailyBranchOperations.csv", index=False)
prod_avail_raw_df.to_csv("cleaned_data/Cleaned_ProductAvailability.csv", index=False)

try:
    orders_df.to_csv("cleaned_data/Cleaned_Orders.csv", index=False)
except NameError:
    pass

print("تم حفظ جميع الجداول المنظفة بنجاح داخل مجلد: cleaned_data/")

تم حفظ جميع الجداول المنظفة بنجاح داخل مجلد: cleaned_data/

In [40]:
import glob
import os
import pandas as pd

cleaned_files = glob.glob("cleaned_data/*.csv")

print(f"تم العثور على {len(cleaned_files)} ملفات في cleaned_data:\n")

for file_path in cleaned_files:
  file_name = os.path.basename(file_path)
  df = pd.read_csv(file_path)

  null_count = df.isnull().sum().sum()
  duplicates_count = df.duplicated().sum()

  print(f"--- فحص ملف: {file_name} ---")
  print(f"• إجمالي الصفوف: {len(df)}")
  print(f"• إجمالي الأعمدة: {len(df.columns)}")
  print(f"• عدد القيم المفقودة (Nulls): {null_count}")
  print(f"• عدد الصفوف المكررة: {duplicates_count}")

  if null_count > 0:
    print("  تنبيه! الأعمدة التي بها Nulls:")
    print(df.isnull().sum()[df.isnull().sum() > 0])
  else:
    print("  حالة النظافة: سليم 100% (Clean)")
  print("-" * 40)

تم العثور على 6 ملفات في cleaned_data:

--- فحص ملف: Branches.csv ---
• إجمالي الصفوف: 20
• إجمالي الأعمدة: 6
• عدد القيم المفقودة (Nulls): 0
• عدد الصفوف المكررة: 0
  حالة النظافة: سليم 100% (Clean)
----------------------------------------
--- فحص ملف: Cleaned_DailyBranchOperations.csv ---
• إجمالي الصفوف: 3620
• إجمالي الأعمدة: 7
• عدد القيم المفقودة (Nulls): 0
• عدد الصفوف المكررة: 0
  حالة النظافة: سليم 100% (Clean)
----------------------------------------
--- فحص ملف: Cleaned_OrderItems.csv ---
• إجمالي الصفوف: 36650
• إجمالي الأعمدة: 7
• عدد القيم المفقودة (Nulls): 0
• عدد الصفوف المكررة: 0
  حالة النظافة: سليم 100% (Clean)
----------------------------------------
--- فحص ملف: Cleaned_Orders.csv ---
• إجمالي الصفوف: 19000
• إجمالي الأعمدة: 8
• عدد القيم المفقودة (Nulls): 11648
• عدد الصفوف المكررة: 0
  تنبيه! الأعمدة التي بها Nulls:
DeliveryMinutes    11648
dtype: int64
----------------------------------------
--- فحص ملف: Cleaned_ProductAvailability.csv ---
• إجمالي الصفوف: 12411
• إجمالي الأعمدة: 8
• عدد القيم المفقودة (Nulls): 0
• عدد الصفوف المكررة: 0
  حالة النظافة: سليم 100% (Clean)
----------------------------------------
--- فحص ملف: Products.csv ---
• إجمالي الصفوف: 33
• إجمالي الأعمدة: 7
• عدد القيم المفقودة (Nulls): 0
• عدد الصفوف المكررة: 0
  حالة النظافة: سليم 100% (Clean)
----------------------------------------